### ISSUE TITLE
[BUG]: Debian image uses debian:bullseye-slim instead of debian:bullseye

### ISSUE THREAD

**Issue by luisrudge** [ImBIOS/bun-node#8]
### Description of the bug

I need to use the standard debian image, but I can't with this particular setup

### Environment

n/a

### Steps To Reproduce

https://github.com/ImBIOS/bun-node/blob/main/20/debian/dockerfile#L1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ImBIOS** [comment]
It's just for the build process, the runtime is using the non-slim version.

**Comment by luisrudge** [comment]
Welp! My apologies, then 😅
